### ISSUE TITLE
How to show the embedded view like in the animated gif?

### ISSUE THREAD

**Issue by rraallvv** [chizoba/google-dictionary#1]
I'm not sure if the animated gif in the readme file is outdated but when I select a word in the sample application it opens the web browser instead. Is there a way to get only the word definition data, or have the web view embedded in a popup.

Keep up the good work.

**Comment by chizoba** [comment]
Hi @rraallvv, thanks for reaching out. The readme file is actually up to date. Pertaining to your request, it's possible. It all depends on how you plan to implement it. Send me an email (ogbonnacj2@gmail.com) if you require any help :)
